window.GAME_DATA = {
  meta: {
    title: "Fake Merge Rescue",
    brandLabel: "FAKE MERGE",
    objective: "정답 조합을 머지해서 탐험가를 구하세요.",
    retryLabel: "다시 하기",
    ctaLabel: "Play Now",
    ctaUrl: "#",
    resultLabels: {
      success: "SUCCESS",
      fail: "FAIL",
    },
  },
  assets: {
    backgroundImage: "",
    brandImage: "",
    character: {
      idle: "",
      success: "",
      fail: "",
    },
  },
  layout: {
    portraitBreakpointRatio: 1.15,
  },
  timelineMs: {
    preintro: 1000,
    intro: 1000,
    merge: 700,
    result: 900,
    ctaReveal: 5000,
    total: 6000,
  },
  items: [
    {
      id: "wood",
      label: "나무",
      emoji: "🪵",
      description: "구조용 불씨를 키울 수 있는 마른 장작.",
      accent: "#ad6a2b",
      accentSoft: "rgba(173, 106, 43, 0.22)",
    },
    {
      id: "fire",
      label: "불",
      emoji: "🔥",
      description: "얼어붙은 야영지를 데울 수 있는 불씨.",
      accent: "#ff5f36",
      accentSoft: "rgba(255, 95, 54, 0.24)",
    },
    {
      id: "water",
      label: "물",
      emoji: "💧",
      description: "필요한 자원이지만 지금은 구조에 맞지 않음.",
      accent: "#38a9ff",
      accentSoft: "rgba(56, 169, 255, 0.24)",
    },
  ],
  correctPair: ["wood", "fire"],
  phaseText: {
    preintro: {
      badge: "PreIntro",
      headline: "탐험가가 얼어붙고 있어요. 서둘러 주세요.",
      subline: "위기 연출이 재생 중입니다. 잠시 후 입력이 열립니다.",
      warning: "DANGER",
      caption: "차가운 바람이 점점 더 강해지고 있어요.",
      feedback: "짧은 위기 연출 후, 아이템 두 개를 눌러 머지하세요.",
    },
    intro: {
      badge: "Intro",
      headline: "빠른 머지 한 번이 상황을 바꿀 수 있어요.",
      subline: "구조에 성공하는 조합은 단 하나뿐입니다.",
      warning: "ALERT",
      caption: "아이템이 나타났어요. 신중하게 골라 주세요.",
      feedback: "힌트: 지금 필요한 건 차가움을 이길 열기예요.",
    },
    play: {
      badge: "Play",
      headline: "아이템 두 개를 골라 탐험가를 구하세요.",
      subline: "정답 조합 1개, 오답 조합 2개입니다.",
      warning: "CHOOSE",
      caption: "아이템 하나를 누르고, 하나를 더 누르면 자동 머지됩니다.",
      feedback: "상황이 더 나빠지기 전에 올바른 조합을 선택하세요.",
    },
    merge: {
      badge: "Merge",
      headline: "머지 중...",
      subline: "선택한 두 아이템이 결합되고 있어요.",
      warning: "MERGE",
      caption: "곧바로 결과가 나옵니다.",
      feedback: "머지 결과를 계산하고 있어요.",
    },
    success: {
      badge: "Result",
      headline: "성공. 구조가 완료됐어요.",
      subline: "나무와 불이 탐험가에게 필요한 온기를 만들었습니다.",
      warning: "SAFE",
      caption: "캠프파이어가 켜지며 위기가 진정됩니다.",
      feedback: "정답 머지 성공. 잠시 후 CTA가 활성화됩니다.",
    },
    fail: {
      badge: "Result",
      headline: "잘못된 머지로 상황이 더 나빠졌어요.",
      subline: "오답 조합입니다. 다시 시도하거나 CTA로 전환할 수 있어요.",
      warning: "FAIL",
      caption: "탐험가는 아직 위험한 상태예요.",
      feedback: "정답 조합은 아직 남아 있어요. 한 번 더 시도해 보세요.",
    },
    cta: {
      badge: "CTA",
      headline: "이제 본 게임에서 구조를 이어가 볼까요?",
      subline: "흐름이 살아 있을 때 바로 전환을 유도합니다.",
      warning: "GO",
      caption: "광고 플로우가 끝났어요. 다음 탭을 유도하세요.",
      feedback:
        "Play Now가 활성화됐습니다. 원하면 다시 하기로 한 번 더 플레이할 수도 있어요.",
    },
  },
  integration: {
    emitDomEvents: true,
    hooksGlobalName: "GAME_HOOKS",
  },
};
